name: GitHub Actions Demo
on:
  push:
    branches:
      - git-actions-test
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.1
      - name: Run build with Gradle wrapper
        id: gradle
        run: ./gradlew clean bootJar
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: Package
#          path: build/libs/bot-([0-9]+\.)+jar
#      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "bot/build/libs/bot-0.0.2.jar"
          target: "${{ secrets.REMOTE_DIR }}"
