name: GitHub Actions Demo
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.1
      - name: Run build with Gradle wrapper
        id: gradle
        run: ./gradlew clean bootJar
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: Package
#          path: build/libs/bot-([0-9]+\.)+jar
      - name: List files
        run: ls bot/build/libs
      - name: Copying files to server with scp
        uses: mdallasanta/ssh-scp-deploy@acf9c1fefcda34c0b8b0cb0c0c1b521bf130d8b6
        with:
          local: 'bot/build/libs/'
          remote: '${{ secrets.REMOTE_DIR }}'
          host: ${{secrets.REMOTE_HOST}}
          user: ${{secrets.REMOTE_USER}}
          password: ${{ secrets.SSH_PASSWORD }}
#          key:  ${{secrets.SSH_KEY}}
          pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
          post_upload: echo "This will be executed after the upload!"  # Command to run via ssh after scp upload - REQUIRED false
##          ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
##          scp_options: -v                                              # Flags to use during scp - REQUIRED false - DEFAULT ''